candidate/urls.py
from django.conf.urls import url
from .views import (
    index,
    upload_resume,
    upload_profilepic,
    profile,
    edit_personalinfo,
    edit_profile_description,
    edit_professionalinfo,
    add_language,
    edit_language,
    delete_language,
    add_experience,
    edit_experience,
    delete_experience,
    add_education,
    edit_education,
    delete_education,
    add_technicalskill,
    edit_technicalskill,
    delete_technicalskill,
    add_project,
    edit_project,
    delete_project,
    edit_email,
    job_alert,
    job_alert_results,
    modify_job_alert,
    alerts_list,
    delete_job_alert,
    edit_emailnotifications,
    delete_resume,
    user_password_change,
    messages,
)

app_name = "candidate"

urlpatterns = [
    # url(r'^home/$','home'),
    url(r"^$", index, name="index"),
    url(r"^profile/$", profile, name="profile"),
    url(r"personalinfo/edit/$", edit_personalinfo, name="edit_personalinfo"),
    url(
        r"profile_description/edit/$",
        edit_profile_description,
        name="edit_profile_description",
    ),
    url(r"email/edit/$", edit_email, name="edit_email"),
    url(
        r"professionalinfo/edit/$", edit_professionalinfo, name="edit_professionalinfo"
    ),
    # mobile verify
    # url(r'^mobile/verify/$', verify_mobile, name="verify_mobile"),
    # url(r'^send/mobile_verification_code/$', send_mobile_verification_code, name="send_mobile_verification_code"),
    # language urls
    url(r"language/add/$", add_language, name="add_language"),
    url(
        r"language/edit/(?P<language_id>[a-zA-Z0-9_-]+)/$",
        edit_language,
        name="edit_language",
    ),
    url(
        r"language/delete/(?P<language_id>[a-zA-Z0-9_-]+)/$",
        delete_language,
        name="delete_language",
    ),
    # experience urls
    url(r"experience/add/$", add_experience, name="add_experience"),
    url(
        r"experience/edit/(?P<experience_id>[a-zA-Z0-9_-]+)/$",
        edit_experience,
        name="edit_experience",
    ),
    url(
        r"experience/delete/(?P<experience_id>[a-zA-Z0-9_-]+)/$",
        delete_experience,
        name="delete_experience",
    ),
    # education urls
    url(r"education/add/$", add_education, name="add_education"),
    url(
        r"education/edit/(?P<education_id>[a-zA-Z0-9_-]+)/$",
        edit_education,
        name="edit_education",
    ),
    url(
        r"education/delete/(?P<education_id>[a-zA-Z0-9_-]+)/$",
        delete_education,
        name="delete_education",
    ),
    # techskill urls
    url(r"technicalskill/add/$", add_technicalskill, name="add_technicalskill"),
    url(
        r"technicalskill/edit/(?P<technical_skill_id>[a-zA-Z0-9_-]+)/$",
        edit_technicalskill,
        name="edit_technicalskill",
    ),
    url(
        r"technicalskill/delete/(?P<technical_skill_id>[a-zA-Z0-9_-]+)/$",
        delete_technicalskill,
        name="delete_technicalskill",
    ),
    # project urls
    url(r"project/add/$", add_project, name="add_project"),
    url(
        r"project/edit/(?P<project_id>[a-zA-Z0-9_-]+)/$",
        edit_project,
        name="edit_project",
    ),
    url(
        r"project/delete/(?P<project_id>[a-zA-Z0-9_-]+)/$",
        delete_project,
        name="delete_project",
    ),
    # resume urls
    url(r"upload_resume/$", upload_resume, name="upload_resume"),
    url(r"delete-resume/$", delete_resume, name="delete_resume"),
    url(r"upload_profilepic/$", upload_profilepic, name="upload_profilepic"),
    url(
        r"edit_emailnotifications/$",
        edit_emailnotifications,
        name="edit_emailnotifications",
    ),
    # job alert
    url(r"^alert/create/$", job_alert, name="job_alert"),
    url(r"^alert/list/$", alerts_list, name="alerts_list"),
    url(r"^alert/list/(?P<page_num>[-\w]+)/$", alerts_list),
    url(
        r"^alert/results/(?P<job_alert_id>[a-zA-Z0-9_-]+)/$",
        job_alert_results,
        name="job_alert_results",
    ),
    url(
        r"^alert/modify/(?P<job_alert_id>[a-zA-Z0-9_-]+)/$",
        modify_job_alert,
        name="modify_job_alert",
    ),
    url(
        r"^alert/delete/(?P<job_alert_id>[a-zA-Z0-9_-]+)/$",
        delete_job_alert,
        name="delete_job_alert",
    ),
    url(r"user/password/change/", user_password_change, name="user_password_change"),
    url(r"^messages/$", messages, name="messages"),
]

jobsp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from pjob.views import (
    skill_location_wise_fresher_jobs,
    skill_fresher_jobs,
    skill_location_walkin_jobs,
    register_using_email,
    login_user_email,
    forgot_password,
    user_activation,
    user_reg_success,
    recruiter_profile,
    jobs_by_location,
    jobs_by_skill,
    jobs_by_degree,
    jobs_by_industry,
    full_time_jobs,
    walkin_jobs,
    city_internship_jobs,
    internship_jobs,
    government_jobs,
    each_company_jobs,
    job_industries,
    companies,
    jobposts_by_date,
    # week_calendar,
    job_locations,
    set_password,
    job_skills,
    job_detail,
    # year_calendar,
    # calendar_add_event,
    # calendar_event_list,
    # month_calendar,
    recruiters,
    user_subscribe,
    unsubscribe,
    fresher_jobs_by_skills,
    process_email,
    location_fresher_jobs,
)
from search.views import (
    skill_auto_search,
    city_auto_search,
    custome_search,
    custom_walkins,
    search_slugs,
)
from candidate.views import (
    bounces,
    assessment_changes,
    applicant_unsubscribing,
    applicant_email_unsubscribing,
    question_view,
    assessments_questions,
    alert_subscribe_verification,
)
from recruiter.views import index
from psite.views import (
    contact,
    sitemap,
    get_out,
    pages,
    custom_500,
    sitemap_xml,
    users_login,
    custom_404,
    auth_return,
)
from pjob.views import index as job_list

# from django.contrib import admin


urlpatterns = [
    url(
        r"^(?P<job_title_slug>[a-z0-9-.,*?]+)-(?P<job_id>([0-9])+)/$",
        job_detail,
        name="job_detail",
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-fresher-jobs-in-(?P<city_name>[-\w]+)/$",
        skill_location_wise_fresher_jobs,
        name="skill_location_wise_fresher_jobs",
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-fresher-jobs-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$",
        skill_location_wise_fresher_jobs,
    ),
    url(
        r"^internship-jobs-in-(?P<location>[-\w]+)/$",
        city_internship_jobs,
        name="city_internship_jobs",
    ),
    url(
        r"^internship-jobs-in-(?P<location>[-\w]+)/(?P<page_num>[0-9]+)/$",
        city_internship_jobs,
    ),
    url(
        r"^fresher-jobs-in-(?P<city_name>[-\w]+)/$",
        location_fresher_jobs,
        name="location_fresher_jobs",
    ),
    url(
        r"^fresher-jobs-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$",
        location_fresher_jobs,
        name="location_fresher_jobs",
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-jobs-in-(?P<city_name>[-\w]+)/$",
        custome_search,
        name="custome_search",
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-jobs-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$",
        custome_search,
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-walkins-in-(?P<city_name>[-\w]+)/$",
        custom_walkins,
        name="custom_walkins",
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-walkins-in-(?P<city_name>[-\w]+)/(?P<page_num>[0-9]+)/$",
        custom_walkins,
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-fresher-jobs/$",
        skill_fresher_jobs,
        name="skill_fresher_jobs",
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-fresher-jobs/(?P<page_num>[0-9]+)/$",
        skill_fresher_jobs,
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-walkins/(?P<page_num>[0-9]+)/$",
        skill_location_walkin_jobs,
    ),
    url(
        r"^(?P<skill_name>[-\w]+)-walkins/$",
        skill_location_walkin_jobs,
        name="skill_walkin_jobs",
    ),
    url(
        r"^walkins-in-(?P<skill_name>[-\w]+)/(?P<page_num>[0-9]+)/$",
        skill_location_walkin_jobs,
    ),
    url(
        r"^walkins-in-(?P<skill_name>[-\w]+)/$",
        skill_location_walkin_jobs,
        name="location_walkin_jobs",
    ),
    url(r"^skill-auto/$", skill_auto_search),
    url(r"^city-auto/$", city_auto_search),
    url(r"^get/search-slugs/$", search_slugs, name="get_search_slugs"),
    # url(r'^admin/', admin.site.urls),# Here's the typo
    url(r"^search/", include("search.urls", namespace="search")),
    url(r"^skill-auto/$", skill_auto_search),
    url(
        r"^unsubscribe_email/(?P<email_type>([a-z0-9-])+)/(?P<message_id>[a-zA-Z0-9_-]+.*?)/$",
        applicant_email_unsubscribing,
        name="applicant_email_unsubscribing",
    ),
    url(
        r"^email-unsubscribe/(?P<message_id>[a-zA-Z0-9_-]+.*?)/$",
        applicant_unsubscribing,
        name="applicant_unsubscribing",
    ),
    url(r"^social/", include("social.urls", namespace="social")),
    url(r"^dashboard/", include("dashboard.urls", namespace="dashboard")),
    url(r"^recruiter/", include("recruiter.urls", namespace="recruiter")),
    url(r"^agency/", include("agency.urls", namespace="agency")),
    url(r"^tellme/", include("tellme.urls")),
    url(r"^post-job/$", index, name="post_job"),
    url(r"^bounces/$", bounces),
    url(r"registration/using_email/$", register_using_email, name="register_email"),
    url(r"applicant/login/$", login_user_email, name="login_user"),
    url(r"user/forgot_password/$", forgot_password, name="forgot_password"),
    url(
        r"^user/set_password/(?P<user_id>[0-9]+)/(?P<passwd>[a-zA-Z0-9]+)/$",
        set_password,
        name="set_password",
    ),
    url(
        r"^user/activation/(?P<user_id>[a-zA-Z0-9]+)/$",
        user_activation,
        name="user_activation",
    ),
    url(r"^user/reg_success/$", user_reg_success, name="user_reg_success"),
    url(r"^social/user/update/$", user_reg_success, name="social_user"),
    url(r"^recruiters/page/(?P<page_num>[0-9]+)/$", recruiters),
    url(
        r"^recruiters/(?P<recruiter_name>[a-zA-Z0-9_-]+.*?)/(?P<page_num>[0-9]+)/$",
        recruiter_profile,
    ),
    url(
        r"^recruiters/(?P<recruiter_name>[a-zA-Z0-9_-]+.*?)/$",
        recruiter_profile,
        name="recruiter_profile",
    ),
    url(
        r"^(?P<job_type>[-\w]+)-jobs-by-skills/$",
        fresher_jobs_by_skills,
        name="fresher_jobs_by_skills",
    ),
    url(
        r"^(?P<job_type>[-\w]+)-by-location/$",
        jobs_by_location,
        name="jobs_by_location",
    ),
    url(r"^jobs-by-skill/$", jobs_by_skill, name="jobs_by_skill"),
    url(r"^jobs-by-industry/$", jobs_by_industry, name="jobs_by_industry"),
    url(r"^jobs-by-degree/$", jobs_by_degree, name="jobs_by_degree"),
    url(r"^full-time-jobs/$", full_time_jobs, name="full_time_jobs"),
    url(r"^full-time-jobs/(?P<page_num>[0-9]+)/$", full_time_jobs),
    url(r"^walkin-jobs/$", walkin_jobs, name="walkin_jobs"),
    url(r"^walkin-jobs/(?P<page_num>[0-9]+)/$", walkin_jobs),
    url(r"^internship-jobs/$", internship_jobs, name="internship_jobs"),
    url(r"^internship-jobs/(?P<page_num>[0-9]+)/$", internship_jobs),
    url(r"^government-jobs/$", government_jobs, name="government_jobs"),
    url(r"^government-jobs/(?P<page_num>[0-9]+)/$", government_jobs),
    url(
        r"^assessment/question/view/(?P<que_id>[0-9]+)/$",
        question_view,
        name="question_view",
    ),
    url(
        r"^assessment-questions/$", assessments_questions, name="assessments_questions"
    ),
    url(r"^assessment-questions/(?P<page_num>[0-9]+)/$", assessments_questions),
    url(r"^assessment-changes/$", assessment_changes),
    url(r"^sitemap.xml$", sitemap_xml, name="sitemap_xml"),
    url(r"^login/$", users_login, name="users_login"),
    url(r"^contact/$", contact, name="contact"),
    url(
        r"^unsubscribe/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$",
        unsubscribe,
        name="unsubscribe",
    ),
    url(r"^sitemap/$", sitemap, name="sitemap"),
    url(r"^sitemap/(?P<page_num>[0-9]+)/$", sitemap, name="sitemap"),
    url(r"^logout/$", get_out, name="get_out"),
    url(
        r"^(?P<company_name>[-\w]+)-job-openings/(?P<page_num>[0-9]+)/$",
        each_company_jobs,
    ),
    url(
        r"^(?P<company_name>[-\w]+)-job-openings/$",
        each_company_jobs,
        name="company_jobs",
    ),
    url(
        r"^(?P<industry>[-\w]+)-industry-jobs/$", job_industries, name="job_industries"
    ),
    url(r"^(?P<industry>[-\w]+)-industry-jobs/(?P<page_num>[0-9]+)/$", job_industries),
    url(r"^jobs-for-(?P<industry>[-\w]+)-industry/$", job_industries),
    url(
        r"^jobs-for-(?P<industry>[-\w]+)-industry/(?P<page_num>[0-9]+)/$",
        job_industries,
    ),
    url(r"^(?P<skill>[a-z0-9-.*?]+)-jobs/$", job_skills, name="job_skills"),
    url(r"^(?P<skill>[a-z0-9-.*?]+)-jobs/(?P<page_num>[0-9]+)/$", job_skills),
    url(r"^page/(?P<page_name>([a-z0-9-])+)/$", pages, name="pages"),
    url(r"^companies/(?P<page_num>[0-9]+)/$", companies),
    url(r"companies/$", companies, name="companies"),
    url(r"^", include("candidate.urls", namespace="my")),
    url(
        r"jobposts/year/(?P<year>\w{0,})/month/(?P<month>\w{0,})/date/(?P<date>\w{0,})/$",
        jobposts_by_date,
        name="jobposts_by_date",
    ),
    url(
        r"jobposts/year/(?P<year>\w{0,})/month/(?P<month>\w{0,})/date/(?P<date>\w{0,})/(?P<page_num>[0-9]+)/$",
        jobposts_by_date,
    ),
    # url(
    #     r"calendar/(?P<year>\w{0,})/month/(?P<month>\w{0,})/week/(?P<week>\w{0,})/$",
    #     week_calendar,
    #     name="week_calendar",
    # ),
    url(r"tickets/", include("tickets.urls", namespace="tickets")),
    url(r"^jobs-in-(?P<location>[-\w]+)/$", job_locations, name="job_locations"),
    url(r"^jobs-in-(?P<location>[-\w]+)/(?P<page_num>[0-9]+)/$", job_locations),
    url(r"^jobs-for-(?P<skill>[-\w]+)/$", job_skills),
    # url(r"calendar/(?P<year>\w{0,})/$", year_calendar, name="year_calendar"),
    # url(r"calendar/add/event/$", calendar_add_event, name="calendar_add_event"),
    # url(r"calendar/event/list/$", calendar_event_list, name="calendar_event_list"),
    # url(
    #     r"calendar/(?P<year>\w{0,})/month/(?P<month>\w{0,})/$",
    #     month_calendar,

pjob/urls.py
from django.conf.urls import url
from pjob.views import (
    index,
    job_apply,
    user_applied_job,
    jobs_applied,
    job_add_event,
    get_skills,
)

app_name = "pjob"

urlpatterns = [
    url(r"^$", index, name="index"),
    # url(r'(?P<jp>((\w{0,})-(?P<jid>(\w{0,})))+)(?:\/(?P<uid>[A-Za-z0-9]+))?/$','job_detail'),
    url(r"apply/(?P<job_id>[a-zA-Z0-9_-]+)/$", job_apply, name="job_apply"),
    url(r"applied_for/$", user_applied_job, name="user_applied_job"),
    url(r"applied/$", jobs_applied, name="jobs_applied"),
    url(r"add/event/$", job_add_event, name="job_add_event"),
    url(r"get_skills/$", get_skills, name="get_skills"),
    url(r"^(?P<page_num>[0-9]+)/$", index),
]

templates/alert/list.html
{% extends "base.html" %}
{% load page_tags %}
{% load searchtags %}
{% block block_title %}
{% include "meta_data/job_alert.html" %}
{% endblock %}
{% block block_canonical_tag %}
  {% if current_page|slugify == '1'|slugify %}
    {% else %}
    <link rel="prev" href="https://peeljobs.com{{ current_url }}{% if prev_page != 1 %}{{ prev_page }}/{% endif %}" />
  {% endif %}
  {% if current_page <= last_page %}
    {% if current_page == last_page %}
    {% else %}
      <link rel="next" href="https://peeljobs.com{{ current_url }}{{ current_page| add:"1" }}/" />
    {% endif %}
  {% endif %}
{% endblock %}
{% block page_search_block %}
{% show_search_filter %}
{% endblock %}
{% block base %}
<style type="text/css">
  .job_alert_details_row {
  line-height: 24px;
  }
  .job_alert_details_row .details_left {
  width: 50%;
  }
  .job_alert_details_row .details_right {
  width: 50%;
  }
  .job_alert_details_row label {
  width: 100px !important;
  }
  .main_container .left_container .job_alert_result_container .detail_container .detail {
    border: none;
  }
</style>
    <!-- main_container starts here -->
      <div class="row mar_lr_0 main_container">
        <div class="container">

        <!-- breadcrumb_section starts here -->
        <div class="breadcrumb_section row mar_lr_0">
          <nav>
            <ol class="cd-breadcrumb triangle">
             <li>
              <a href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}" class="name">
                <span class="name">Home</span>
              </a>
            </li>
            <li class="current">
              <span href="{% url 'my:alerts_list' %}" class="job_detail">
                <span class="name">Job Alert</span>
              </span>
            </li>
            </ol>
          </nav>
        </div>
        <!-- breadcrumb_section ends here -->

          <div class="row mar_lr_0">
            <div class="col-md-9 left_container">
              <!-- side_filter_section starts here -->
              <div class="row">

                <!-- job_list_section starts here -->
                <div class="col-md-12">
                <!--job_alert_result_container starts heere -->
          <a href="{% url 'my:job_alert' %}" target="_blank" class="add_new_alert pull-right">Create Job Alert</a>                  <div class="clearfix"></div>
          <h4 class="job_list_header text-center text-uppercase"> Job Alerts</h4>
          {%  for job_alert in job_alerts %}
                  <div class="job_alert_result_container" style="margin-bottom:15px;background:white">
                <div class="pull-right actions">
                  <a href="{% url 'my:modify_job_alert' job_alert.id %}" class="edit"><i class="fa fa-edit"></i></a>
                  <a href="#" class="alert-delete del" id="{{ job_alert.id }}"><i class="fa fa-trash"></i></a>
                </div>
                <div class="title"><a href="{% url 'my:job_alert_results' job_alert.id %}" class='title'>{{ job_alert.name }}</a></div>
                <div class="detail_container">
                <div class="row">
                <div class="col-md-6">
                  <div class="detail">
                    <div class="detail_title">Skills <span class="pull-right">:</span></div>
                    <div class="detail_content">
                      {% for skill in job_alert.skill.all %}
                      <a href="{{ skill.get_job_url }}" target="_blank">{{ skill.name }}</a>{% if forloop.last %}{% else %},&nbsp;{% endif %}
                      {% endfor %}
                    </div>
                  </div>
                  <div class="detail">
                    <div class="detail_title">Location(s) <span class="pull-right">:</span></div>
                    <div class="detail_content">
                      {% if job_alert.location.all %}
                      {% for location in job_alert.location.all %}
                      <a href="{{ location.get_job_url }}" target="_blank">{{ location.name }}</a>
                      {% if forloop.last %}{% else %}, {% endif %}
                      {% endfor %}
                      {% else %}
                      Not Specified
                      {% endif %}
                    </div>
                  </div>
                  <div class="detail">
                    <div class="detail_title">Salary <span class="pull-right">:</span></div>
                    <div class="detail_content">
                      {% if job_alert.min_salary and job_alert.max_salary %}<i class="fa fa-inr" aria-hidden="true"></i> {{ job_alert.min_salary|get_formatted_salary }} - {{ job_alert.max_salary|get_formatted_salary }}
                      {% elif job_alert.min_salary %}
                      <i class="fa fa-inr" aria-hidden="true"></i> {{ job_alert.min_salary|get_formatted_salary }} 
                      {% elif job_alert.max_salary%}
                      <i class="fa fa-inr" aria-hidden="true"></i> {{ job_alert.max_salary|get_formatted_salary }}
                      {% else %}
                      Not Specified
                     {% endif %}
                    </div>
                  </div>
                  </div>
                  <div class="col-md-6">
                  <div class="detail">
                    <div class="detail_title">Experience <span class="pull-right">:</span></div>
                    <div class="detail_content">
                   {% if job_alert.min_year and job_alert.max_year %}
                    {{ job_alert.min_year }} - {{ job_alert.max_year }} Year(s)
                    {% elif job_alert.min_year %}
                    {{ job_alert.min_year }} Year(s)
                    {% elif job_alert.max_year %}
                    {{ job_alert.max_year }} Year(s)
                    {% else %}
                    Not Specified
                    {% endif %}

                    </div>
                  </div>
                  <div class="detail">
                    <div class="detail_title">Job Role <span class="pull-right">:</span></div>
                    <div class="detail_content">{% if not job_alert.role %}Not Specified{% else %}
                      {{ job_alert.role }}{% endif %}
                    </div>
                  </div>
                  <div class="detail">
                    <div class="detail_title">Industry <span class="pull-right">:</span></div>
                    <div class="detail_content">{% if job_alert.industry.all %}{% for industry in job_alert.industry.all %}
                      {{ industry.name }}
                      {% if forloop.last %}{% else %}, {% endif %}{% endfor %}{% else %}Not Specified{% endif %}
                    </div>
                  </div>
                  </div>
                  <br clear="all">
                  </div>
                </div>
              </div>
              {% empty %}
              <div class="no-results text-center">
        <!--                  <h1>{{ message_type }},</h1>
          <h4>{{ message }}</h4>!-->
          <div class="job_alert_result_container" style="margin-bottom:15px;background:white;">
        <h3>No Job Alerts available</h3>
        <h6>Create job alert and get job notifications</h6>
         <a href="{% url 'my:job_alert' %}" style="font-size:11px;" target="_blank" class="add_new_alert">Create Job Alert and get notifications</a>
        </div>
      </div>
              {% endfor %}
              <!-- job_alert_result_container ends here --> 
            </div>
            <!-- job_list_section ends here -->
          </div>
        </div>
        {% include 'left_menu.html' %}
      </div>
    </div>
  </div>
  <!-- main_container ends here -->
{% block pj_info %}
  <div class="col-md-2 col-sm-8 col-xs-8 about">
  </div>
{% endblock %}
{% endblock %}
{% block 'extra_js' %}
<script type="text/javascript">
 $("select#job_skills").select2({placeholder: "Select here", maximumSelectionSize: 100});
   $(".alert-delete").click(function (e) {
      e.preventDefault();
      id = $(this).attr('id')
       $('#block_question').text('Do you want to delete Alert?')
            $('#block_question').dialog({
                modal: true,
                draggable: false,
                title: "Info!!",
                buttons: [
                    {
                        text: "Yes",
                        click: function () {
                            $(this).dialog("close");
                                  $.post('/alert/delete/' + id + '/', $("form#educationform").serialize(), function (data) {
                                      if (data.error) {
                                          if (data.response_message) {
                                              open_dialog(data.response_message, 'Error!')
                                          }
                                          else{
                                              open_dialog('Something went wrong', 'Error!')
                                            }
                                      } else {
                                          open_dialog_with_url('Job Alert Deleted Successfully', 'Success!!!', ".")
                                      }
                                  }, 'json');
                                }
                 },
                    {
                        text: "No",
                        click: function () {
                            $(this).dialog("close");
                        }
                    }
                ]
            });
          })
  $("select.cities").select2({placeholder: "Select the city", maximumSelectionSize: 100});

  $("select.skills").select2({placeholder: "Select the skill", maximumSelectionSize: 100});
  $("select.industry").select2({placeholder: "Select the  industry", maximumSelectionSize: 100});

  $('#job_skills').empty()
      $('#job_skills').append(new Option('Select a Skill', ''))
      $.getJSON("{% url 'jobs:get_skills' %}", function (data) {
          $.each(JSON.parse(data.response), function (key, field) {
              $('#job_skills').append(new Option(field.fields.name, field.pk))
          })
      });
</script>
{% endblock %}